# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AOPOD Bing Images
email: aopodcom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is build for keeping Bing images
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: aopodcom
github_username:  aopod

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Custom
main_site: 'AOPOD'
main_site_url: 'http://www.aopod.com'
ao_assets_path: '/assets'
ao_all_js: []

# Build settings
markdown: kramdown
